// automatically generated by the FlatBuffers compiler, do not modify

package httpbridge

const (
	TxFrameTypeHeader = 0
	TxFrameTypeBody = 1
	TxFrameTypeAbort = 2
	TxFrameTypePause = 3
	TxFrameTypeResume = 4
)

var EnumNamesTxFrameType = map[int]string{
	TxFrameTypeHeader:"Header",
	TxFrameTypeBody:"Body",
	TxFrameTypeAbort:"Abort",
	TxFrameTypePause:"Pause",
	TxFrameTypeResume:"Resume",
}

