// automatically generated by the FlatBuffers compiler, do not modify

package httpbridge

const (
	TxFrameFlagsFinal = 1
)

var EnumNamesTxFrameFlags = map[int]string{
	TxFrameFlagsFinal:"Final",
}

