// automatically generated by the FlatBuffers compiler, do not modify

package httpbridge

const (
	TxHttpVersionHttp10 = 0
	TxHttpVersionHttp11 = 1
	TxHttpVersionHttp2 = 2
)

var EnumNamesTxHttpVersion = map[int]string{
	TxHttpVersionHttp10:"Http10",
	TxHttpVersionHttp11:"Http11",
	TxHttpVersionHttp2:"Http2",
}

